version: '3.8'
services:
  # Python API service
  python-api:
    build: .
    ports:
      - "0.0.0.0:5000:5000"
    environment:
      API_TOKEN: 'carlos89-api-token'
      DEBUG: 'False'
    restart: always
    volumes:
      - ./logs:/app/logs

networks:
  default:
    driver: bridge 