version: '3.8'
services:
  # Python API service
  python-api:
    build: .
    container_name: python-api
    ports:
      - "80:5000"
    environment:
      - API_TOKEN=carlos89-api-token
      - DEBUG=False
    restart: always

networks:
  default:
    driver: bridge 