version: '3.8'
services:
  # Python API service
  python-api:
    build: .
    container_name: python-api
    ports:
      - "5000:5000"
    environment:
      - API_TOKEN=carlos89-api-token
      - DEBUG=False
    restart: always
    volumes:
      - type: bind
        source: ./logs
        target: /app/logs

networks:
  default:
    driver: bridge 